# @package _global_

defaults:
  - classification_base


dataset:
  name: livecell
  simple_cls:
    _target_: datasets.livecell.livecell.LCSimpleDataset

  set_cls:
    _target_: datasets.livecell.livecell.LCSetDataset

backbone:
  _target_: backbones.resnet.ResNet34

#backbone:
#  _target_: backbones.fcnet.FCNet
#  layer_dim: [ 512, 512]  

train_classes: 4

n_way: 4
n_shot: 5
n_query: 15

 