defaults:
  - dataset: tabula_muris
  - method: maml

model: FCNet
n_way: 2
n_shot: 3
n_query: 4

mode: train

exp:
  name: "maml-test"
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: Adam
lr: 0.001
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

wandb:
  project: dl-bio
  entity: s194378
  mode: "online" # Can set to offline, disabled

iter_num: 10
